# Generated by Django 4.1.7 on 2023-05-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_alter_cashtransfers_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransfers',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
