# Generated by Django 4.1.7 on 2023-05-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_cashtransfers_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransfers',
            name='direction',
            field=models.CharField(max_length=15),
        ),
    ]
